services:
  app:
    image: ewdhp/mserver-dev:latest
    container_name: mserver-dev-container
    ports:
      - "5000-5001:5000-5001"
    volumes:
      - nuget-cache:/root/.nuget/packages
      - ./aspnetapp.pfx:/https/aspnetapp.pfx:ro
    working_dir: /app/MServer
    command: dotnet run --urls http://0.0.0.0:5000;http://0.0.0.0:5001
    extra_hosts:
      - "host.docker.internal:host-gateway"
volumes:
  nuget-cache:
